type Query {
  "登录"
  login(loginInput: LoginInput): Login
  "通过refresh_token换取access_token"
  accessToken(refreshTokenInput: String): Login
  "退出登录"
  logout(refreshTokenInput: String): String
  "退出全部设备"
  logoutFromAll: String
  "通过邮件验证身份，用于激活账号与重置密码"
  sendValidate(sendValidateInput: SendValidateInput): String
}

type Mutation {
  "账号注册"
  register(registerInput: RegisterInput): String
}

"登录输入参数"
input LoginInput {
  "账号类型、手机、邮箱"
  type: AccountType!
  "密码"
  password: String!
  "邮箱"
  email: String
  "国家码"
  phoneNumber: String
  "国家"
  countryCode: CountryCode
}

"登录返回参数"
type Login {
  "令牌"
  token: String
  "当token过期时通过refreshToken换取新的token"
  refreshToken: String
  "过期时间"
  expiresIn: Int
}

"发送验证码"
input SendValidateInput {
  "图片验证码"
  imgCode: String!
  "邮箱"
  email: String
  "手机"
  phoneNumber: String
  "账号类型"
  type: AccountType!
}

"账号注册"
input RegisterInput {
  "手机"
  phoneNumber: String
  "国家"
  countryCode: CountryCode
  "邮箱"
  email: String
  "密码"
  password: String!
  "验证码"
  code: String!
  "注册方式"
  type: AccountType!
}

enum AccountType {
  "手机"
  phone
  "邮箱"
  email
}

"国家code"
enum CountryCode {
  AC
  AD
  AE
  AF
  AG
  AI
  AL
  AM
  AO
  AR
  AS
  AT
  AU
  AW
  AX
  AZ
  BA
  BB
  BD
  BE
  BF
  BG
  BH
  BI
  BJ
  BL
  BM
  BN
  BO
  BQ
  BR
  BS
  BT
  BW
  BY
  BZ
  CA
  CC
  CD
  CF
  CG
  CH
  CI
  CK
  CL
  CM
  CN
  CO
  CR
  CU
  CV
  CW
  CX
  CY
  CZ
  DE
  DJ
  DK
  DM
  DO
  DZ
  EC
  EE
  EG
  EH
  ER
  ES
  ET
  FI
  FJ
  FK
  FM
  FO
  FR
  GA
  GB
  GD
  GE
  GF
  GG
  GH
  GI
  GL
  GM
  GN
  GP
  GQ
  GR
  GT
  GU
  GW
  GY
  HK
  HN
  HR
  HT
  HU
  ID
  IE
  IL
  IM
  IN
  IO
  IQ
  IR
  IS
  IT
  JE
  JM
  JO
  JP
  KE
  KG
  KH
  KI
  KM
  KN
  KP
  KR
  KW
  KY
  KZ
  LA
  LB
  LC
  LI
  LK
  LR
  LS
  LT
  LU
  LV
  LY
  MA
  MC
  MD
  ME
  MF
  MG
  MH
  MK
  ML
  MM
  MN
  MO
  MP
  MQ
  MR
  MS
  MT
  MU
  MV
  MW
  MX
  MY
  MZ
  NA
  NC
  NE
  NF
  NG
  NI
  NL
  NO
  NP
  NR
  NU
  NZ
  OM
  PA
  PE
  PF
  PG
  PH
  PK
  PL
  PM
  PR
  PS
  PT
  PW
  PY
  QA
  RE
  RO
  RS
  RU
  RW
  SA
  SB
  SC
  SD
  SE
  SG
  SH
  SI
  SJ
  SK
  SL
  SM
  SN
  SO
  SR
  SS
  ST
  SV
  SX
  SY
  SZ
  TA
  TC
  TD
  TG
  TH
  TJ
  TK
  TL
  TM
  TN
  TO
  TR
  TT
  TV
  TW
  TZ
  UA
  UG
  US
  UY
  UZ
  VA
  VC
  VE
  VG
  VI
  VN
  VU
  WF
  WS
  XK
  YE
  YT
  ZA
  ZM
  ZW
}
